// <auto-generated />
using Authors.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authors.API.Migrations
{
    [DbContext(typeof(CourseLibraryContext))]
    partial class CourseLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Authors.API.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DateOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DateOfBirth = 1279360106496000330L,
                            FirstName = "Berry",
                            LastName = "Griffin Beak Eldritch",
                            MainCategory = "Ships"
                        },
                        new
                        {
                            Id = 102,
                            DateOfBirth = 1277955145728000330L,
                            FirstName = "Nancy",
                            LastName = "Swashbuckler Rye",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 103,
                            DateOfBirth = 1264753115136000330L,
                            FirstName = "Eli",
                            LastName = "Ivory Bones Sweet",
                            MainCategory = "Singing"
                        },
                        new
                        {
                            Id = 104,
                            DateOfBirth = 1264248815616000330L,
                            FirstName = "Arnold",
                            LastName = "The Unseen Stafford",
                            MainCategory = "Singing"
                        },
                        new
                        {
                            Id = 105,
                            DateOfBirth = 1264066560000000330L,
                            FirstName = "Seabury",
                            LastName = "Toxic Reyson",
                            MainCategory = "Maps"
                        },
                        new
                        {
                            Id = 106,
                            DateOfBirth = 1279813091328000330L,
                            FirstName = "Rutherford",
                            LastName = "Fearless Cloven",
                            MainCategory = "General debauchery"
                        },
                        new
                        {
                            Id = 107,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "Atherton",
                            LastName = "Crow Ridley",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 108,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "mike",
                            LastName = "tyson",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 109,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "arthava",
                            LastName = "shinde",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 110,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "shyubham",
                            LastName = "jyoti",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 111,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "baba",
                            LastName = "k",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 112,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "rohan",
                            LastName = "jamanat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 113,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "guddu",
                            LastName = "pandit",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 114,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "kamalesh",
                            LastName = "timwari",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 115,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jahangir",
                            LastName = "aman",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 116,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "tirtha",
                            LastName = "kamat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 117,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jan",
                            LastName = "jani",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 118,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "akshay",
                            LastName = "bhau",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 119,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "udasas",
                            LastName = "rahil",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 120,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "sahil",
                            LastName = "nasy",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 121,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "pyarag",
                            LastName = "aadsd",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8035,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "shyubham",
                            LastName = "jyoti",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8034,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "baba",
                            LastName = "k",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8033,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "rohan",
                            LastName = "jamanat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8032,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "guddu",
                            LastName = "pandit",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8031,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "kamalesh",
                            LastName = "timwari",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8030,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jahangir",
                            LastName = "aman",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8029,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "tirtha",
                            LastName = "kamat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8028,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jan",
                            LastName = "jani",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8027,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "akshay",
                            LastName = "bhau",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8026,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "udasas",
                            LastName = "rahil",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8025,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "sahil",
                            LastName = "nasy",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8024,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "pyarag",
                            LastName = "aadsd",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8023,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "shyubham",
                            LastName = "jyoti",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8022,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "baba",
                            LastName = "k",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8021,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "rohan",
                            LastName = "jamanat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8020,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "guddu",
                            LastName = "pandit",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8019,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "kamalesh",
                            LastName = "timwari",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8018,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jahangir",
                            LastName = "aman",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8017,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "tirtha",
                            LastName = "kamat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8016,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jan",
                            LastName = "jani",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 9001,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "akshay",
                            LastName = "bhau",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8015,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "udasas",
                            LastName = "rahil",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8014,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "sahil",
                            LastName = "nasy",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8013,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "pyarag",
                            LastName = "aadsd",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8012,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "shyubham",
                            LastName = "jyoti",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8011,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "baba",
                            LastName = "k",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8010,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "rohan",
                            LastName = "jamanat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8009,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "guddu",
                            LastName = "pandit",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8007,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "kamalesh",
                            LastName = "timwari",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8006,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jahangir",
                            LastName = "aman",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8117,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "tirtha",
                            LastName = "kamat",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8005,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "jan",
                            LastName = "jani",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8004,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "akshay",
                            LastName = "bhau",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8003,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "udasas",
                            LastName = "rahil",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8002,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "sahil",
                            LastName = "nasy",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = 8001,
                            DateOfBirth = 1280793378816000330L,
                            FirstName = "pyarag",
                            LastName = "aadsd",
                            MainCategory = "Rum"
                        });
                });

            modelBuilder.Entity("Authors.API.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 501,
                            AuthorId = 101,
                            Description = "Commandeering a ship in rough waters isn't easy.  Commandeering it without getting caught is even harder.  In this course you'll learn how to sail away and avoid those pesky musketeers.",
                            Title = "Commandeering a Ship Without Getting Caught"
                        },
                        new
                        {
                            Id = 502,
                            AuthorId = 102,
                            Description = "In this course, the author provides tips to avoid, or, if needed, overthrow pirate mutiny.",
                            Title = "Overthrowing Mutiny"
                        },
                        new
                        {
                            Id = 503,
                            AuthorId = 103,
                            Description = "Every good pirate loves rum, but it also has a tendency to get you into trouble.  In this course you'll learn how to avoid that.  This new exclusive edition includes an additional chapter on how to run fast without falling while drunk.",
                            Title = "Avoiding Brawls While Drinking as Much Rum as You Desire"
                        },
                        new
                        {
                            Id = 504,
                            AuthorId = 104,
                            Description = "In this course you'll learn how to sing all-time favourite pirate songs without sounding like you actually know the words or how to hold a note.",
                            Title = "Singalong Pirate Hits"
                        });
                });

            modelBuilder.Entity("Authors.API.Entities.Course", b =>
                {
                    b.HasOne("Authors.API.Entities.Author", "Author")
                        .WithMany("Courses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Authors.API.Entities.Author", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
